# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFolderToAnalysePath = ClickableQLabel(self.centralwidget)
        self.labelFolderToAnalysePath.setObjectName("labelFolderToAnalysePath")
        self.horizontalLayout.addWidget(self.labelFolderToAnalysePath)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.labelNumberOfFiles = QtWidgets.QLabel(self.centralwidget)
        self.labelNumberOfFiles.setObjectName("labelNumberOfFiles")
        self.horizontalLayout.addWidget(self.labelNumberOfFiles)
        self.pushButtonBrowseFolderToAnalysePath = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBrowseFolderToAnalysePath.setObjectName("pushButtonBrowseFolderToAnalysePath")
        self.horizontalLayout.addWidget(self.pushButtonBrowseFolderToAnalysePath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOutputFile = ClickableQLabel(self.centralwidget)
        self.labelOutputFile.setObjectName("labelOutputFile")
        self.horizontalLayout_2.addWidget(self.labelOutputFile)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonBrowseOutputFilePath = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBrowseOutputFilePath.setObjectName("pushButtonBrowseOutputFilePath")
        self.horizontalLayout_2.addWidget(self.pushButtonBrowseOutputFilePath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.pushButtonAddListWidget = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddListWidget.setObjectName("pushButtonAddListWidget")
        self.verticalLayout.addWidget(self.pushButtonAddListWidget)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButtonDoAnalysis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDoAnalysis.setObjectName("pushButtonDoAnalysis")
        self.verticalLayout.addWidget(self.pushButtonDoAnalysis)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_Template = QtWidgets.QAction(MainWindow)
        self.actionSave_Template.setObjectName("actionSave_Template")
        self.actionLoad_Template = QtWidgets.QAction(MainWindow)
        self.actionLoad_Template.setObjectName("actionLoad_Template")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionSave_Template)
        self.menuFile.addAction(self.actionLoad_Template)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Folder to analyse"))
        self.labelFolderToAnalysePath.setText(_translate("MainWindow", "path"))
        self.labelNumberOfFiles.setText(_translate("MainWindow", "# files"))
        self.pushButtonBrowseFolderToAnalysePath.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Output file"))
        self.labelOutputFile.setText(_translate("MainWindow", "path"))
        self.pushButtonBrowseOutputFilePath.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Attributes"))
        self.pushButtonAddListWidget.setText(_translate("MainWindow", "Add new"))
        self.pushButtonDoAnalysis.setText(_translate("MainWindow", "Go!"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_Template.setText(_translate("MainWindow", "Save Template"))
        self.actionLoad_Template.setText(_translate("MainWindow", "Load Template"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from QDICOMMiner import ClickableQLabel
